services:

  next:
    profiles: ["prod"]
    build:
      context: .
      args:
        - PAYLOAD_SECRET
        - NEXT_PUBLIC_DOMAIN
        - DATABASE_HOST
        - DATABASE_PORT
        - DATABASE_USER
        - DATABASE_PASS
        - DATABASE_TABLE
    restart: unless-stopped
    ports: ["${NEXT_PORT:-3000}:3000"]
    env_file: .env
    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3

  database:
    profiles: ["dev", "prod"]
    image: postgres:17.2
    restart: unless-stopped
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_TABLE}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    ports: ["${DATABASE_PORT:-5432}:5432"]
    volumes:
      - ./data/database:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_TABLE}"]
      interval: 10s
      timeout: 5s
      retries: 5
